CatMy/CatMy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import main.views as main_views
handler404 = main_views.custom_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('users/', include('users.urls')),
    #htpp://127.0.0.1:8000/
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns=[
        path('__debug/__', include(debug_toolbar.urls)),
    ]+ urlpatterns

    urlpatterns+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования котоновостей"
admin.site.index_title = "Котоновости"
admin.site.index_template = 'main/custom_admin.html'

CatMy/main/urls.py
from django.contrib import admin
from django.urls import path

from . import views
urlpatterns = [
    path('', views.index, name='home'),
    path('news/', views.news, name='news'),
    path('account/',views.account, name='account'),
    path('contakt/',views.contakt, name='contakt'),
    path('cats/',views.cats, name='cats'),
    path('sidebar/', views.sidebar),
]

CatMy/main/models.py
from django.db import models

# Create your models here.

CatMy/news/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from django.db.models import Count

class Tag(models.Model):
    title = models.CharField(max_length=80)
    status = models.BooleanField(default=True)
    def __str__(self):
        return self.title

    def tag_count(self):
        count = self.article_set.count()
        #комментарий: когда мы работаем со связанными объектами (foreign_key, m2m, один к одному),
        #мы можем обращаться к связанным таблицам при помощи синтаксиса:
        #связаннаяМодель_set и что-то делать с результатами. В этом примере - мы используем связанные article
        #и вызываем метод count
        return count

    class Meta:
        ordering = ['title','status']
        verbose_name= 'Тэг'
        verbose_name_plural='Тэги'

import datetime
class PublishedToday(models.Manager):
    def get_queryset(self):
        return super(PublishedToday,self).get_queryset().filter(date__gte=datetime.date.today())

from django.core.validators import MinLengthValidator, MaxLengthValidator
class Article(models.Model):
    categories = (('E','Экономика'),
                  ('N','Новости'),
                  ('J','Жилье'),
                  ('R','Разное'))

    #поля                           #models.CASCADE SET_DEFAULT
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField('Название',max_length=50,default='')
    anouncement = models.TextField('Аннотация',max_length=250)
    text = models.TextField('Текст новости')
    date = models.DateTimeField('Дата публикации',auto_now=True)
    category = models.CharField(choices=categories, max_length=20,verbose_name='Категории')
    tags = models.ManyToManyField(to=Tag, blank=True)
    slug = models.SlugField()
    objects = models.Manager()
    published = PublishedToday()

    #методы моделей
    def __str__(self):
        return f'{self.title} от: {str(self.date)[:16]}'

    def get_absolute_url(self):
        return f'/news/show/{self.id}'
    #метаданные модели


    def tag_list(self):
        s = ''
        for t in self.tags.all():
            s+=t.title+' '
        return s

    def image_tag(self):
        image = Image.objects.filter(article=self)
        print('!!!!',image)
        if image:
            return mark_safe(f'<img src="{image[0].image.url}" height="50px" width="auto" />')
        else:
            return '(no image)'


    def get_views(self):
        return self.views.count()


    class Meta:
        ordering = ['title','date']
        verbose_name= 'Новость'
        verbose_name_plural='Новости'


class Image(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(upload_to='article_images/') #лучше добавить поле default !!!

    def __str__(self):
        return self.title

    def image_tag(self):
        if self.image is not None:
            return mark_safe(f'<img src="{self.image.url}" height="50px" width="auto" />')
        else:
            return '(no image)'

class ViewCount(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE, related_name='views')
    ip_address = models.GenericIPAddressField()
    view_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('-view_date',)
        indexes = [models.Index(fields=['-view_date'])]

    def __str__(self):
        return self.article.title

CatMy/main/views.py
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.

from django.utils import translation
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.db import connection, reset_queries
from django.views.decorators.csrf import csrf_exempt


from news.models import Article


def index (request):
    all_news = Article.objects.all().values('author','title')
    article = Article.objects.all().last()
    context = {'articles': all_news, 'article': article}

    return render(request, 'main/index.html', context)


def news(request):
    return render(request, 'main/news.html')

def list(request):
    return render(request, 'main/list.html')

def account(request):
    return render(request, 'main/account.html')


def contakt(request):
    return render(request, 'main/contakt.html')

def cats(request):
    return render(request, 'main/cats.html')



def custom_404(request, exception):
    #return render(request, 'main/sidebar.html')
    return HttpResponse('Котики работают над этим: {exception}')

def sidebar(request):
    return render(request,'main/sidebar.html')

CatMy/main/templates/main/account.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title> {{title}} </title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <script src="https://kit.fontawesome.com/a97047fead.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
</head>

<style>

</style>

<body>
{% include 'main/sidebar.html' %}
    <div class="container" >
        <div class="row">
            <h1> Аккаунт котика </h1>
        </div>
    </div>
    <hr>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <fieldset class="field">
                    <legend class="text-center"> Авторизация </legend>
                        <form>
                            <div class="form-group">
                                <label for="exampleInputEmail1"> Введите Email </label>
                                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Eemail">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1"> Введите пароль </label>
                                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                            </div>
                            <br>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-secondary"> Войти </button>
                            </div>
                        </form>
                </fieldset>
            </div>
    </div>

</body>
</html>

CatMy/main/templates/main/base.html
{% load i18n static %}<!DOCTYPE html>
{% load static %}
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
{% block dark-mode-vars %}
  <link rel="stylesheet" href="{% static "admin/css/dark_mode.css" %}">
  <script src="{% static "admin/js/theme.js" %}" defer></script>
{% endblock %}
{% if not is_popup and is_nav_sidebar_enabled %}
  <link rel="stylesheet" href="{% static "admin/css/nav_sidebar.css" %}">
  <script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script>
{% endif %}
{% block extrastyle %}
       <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    {% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="{% static "admin/css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
</head>

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">
<a href="#content-start" class="skip-to-content-link">{% translate 'Skip to main content' %}</a>
<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    {% block header %}
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% translate 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% translate 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% translate 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% translate 'Change password' %}</a> /
                {% endif %}
                <form id="logout-form" method="post" action="{% url 'admin:logout' %}">
                    {% csrf_token %}
                    <button type="submit">{% translate 'Log out' %}</button>
                </form>
                {% include "admin/color_theme_toggle.html" %}
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    {% endblock %}
    <!-- END Header -->
    {% block nav-breadcrumbs %}
      <nav aria-label="{% translate 'Breadcrumbs' %}">
        {% block breadcrumbs %}
          <div class="breadcrumbs">
            <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
            {% if title %} &rsaquo; {{ title }}{% endif %}
          </div>
        {% endblock %}
      </nav>
    {% endblock %}
    {% endif %}

    <div class="main" id="main">
      {% if not is_popup and is_nav_sidebar_enabled %}
        {% block nav-sidebar %}
          {% include "admin/nav_sidebar.html" %}
        {% endblock %}
      {% endif %}
      <div id="content-start" class="content" tabindex="-1">
        {% block messages %}
          {% if messages %}
            <ul class="messagelist">{% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
            {% endfor %}</ul>
          {% endif %}
        {% endblock messages %}
        <!-- Content -->
        <div id="content" class="{% block coltype %}colM{% endblock %}">
          {% block pretitle %}{% endblock %}
          {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
          {% block content_subtitle %}{% if subtitle %}<h2>{{ subtitle }}</h2>{% endif %}{% endblock %}
          {% block content %}
            {% block object-tools %}{% endblock %}
            {{ content }}
          {% endblock %}
          {% block sidebar %}{% endblock %}
          <br class="clear">
        </div>
        <!-- END Content -->
        {% block footer %}<div id="footer"></div>{% endblock %}
      </div>
    </div>
</div>
<!-- END Container -->

<!-- SVGs -->
<svg xmlns="http://www.w3.org/2000/svg" class="base-svgs">
  <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-auto"><path d="M0 0h24v24H0z" fill="currentColor"/><path d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-2V4a8 8 0 1 0 0 16z"/></symbol>
  <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-moon"><path d="M0 0h24v24H0z" fill="currentColor"/><path d="M10 7a7 7 0 0 0 12 4.9v.1c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2h.1A6.979 6.979 0 0 0 10 7zm-6 5a8 8 0 0 0 15.062 3.762A9 9 0 0 1 8.238 4.938 7.999 7.999 0 0 0 4 12z"/></symbol>
  <symbol viewBox="0 0 24 24" width="1rem" height="1rem" id="icon-sun"><path d="M0 0h24v24H0z" fill="currentColor"/><path d="M12 18a6 6 0 1 1 0-12 6 6 0 0 1 0 12zm0-2a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM11 1h2v3h-2V1zm0 19h2v3h-2v-3zM3.515 4.929l1.414-1.414L7.05 5.636 5.636 7.05 3.515 4.93zM16.95 18.364l1.414-1.414 2.121 2.121-1.414 1.414-2.121-2.121zm2.121-14.85l1.414 1.415-2.121 2.121-1.414-1.414 2.121-2.121zM5.636 16.95l1.414 1.414-2.121 2.121-1.414-1.414 2.121-2.121zM23 11v2h-3v-2h3zM4 11v2H1v-2h3z"/></symbol>
</svg>
<!-- END SVGs -->
</body>
</html>

CatMy/main/templates/main/base_template.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title> {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <script src="https://kit.fontawesome.com/a97047fead.js" crossorigin="anonymous"></script>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block head %}{% endblock %}

</head>
<body>


<div class="row" style="height: 100vh;">
    <div class="col-sm-3">
        <div class="sticky-top">
            {% block sidebar %} {% include 'main/sidebar.html' %} {% endblock %}
        </div>
    </div>
    <div class="col-sm-9">
        <div class="text-center">
            <h1>CatNews - все самое интересное из мира котиков</h1>
        </div>
        <hr>
    {% block content %}
        <div class="row">
            <div class="single_news">
                <div class="p-4 p-md-5 text-Indigo rounded">
                    <div class="col-md-6 px-0">
                        <h1 class="display-4 fst-italic">Последняя новость</h1>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
    </div>
</div>

<div class="row">
    {% block foot %}
    {% endblock %}
</div>
</body>
</html>

CatMy/main/templates/main/cats.html
{% extends 'main/base_template.html' %}
{% load static %}
{% load bootstrap5 %}
{% block title %} Главная страница {% endblock %}

{% block content %}
<!-- jQuery !-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>
<!-- jQuery UI !-->
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script>
  $(function() {
    $("#search_input").autocomplete({
      source: "search_auto/",
      select: function (event, ui) { //item selected
        AutoCompleteSelectHandler(event, ui)
      },
      minLength: 2,
    });
  });

  function AutoCompleteSelectHandler(event, ui)
  {
    var selectedObj = ui.item;
  }
</script>


<div class="content_center">
    <div class="row">
        <div class="text-center">
            <h2> В CatNews собрались самые мудрые котики, чтобы вы всегда получали самые актуальные котоновости. </h2>
            <br>
            <h3> Главные котики: </h3>
            <img src="{% static 'main' %}/img/cat1.jpg" width="20%">
            <img src="{% static 'main' %}/img/cat2.jpg" width="20%">
        </div>
    </div>
</div>
{% endblock %}

CatMy/main/templates/main/contakt.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title> {{title}} </title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <script src="https://kit.fontawesome.com/a97047fead.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
</head>

<body>
{% include 'main/sidebar.html' %}
<div class="container" >
    <div class="row">
        <h1> Контакты </h1>
    </div>
</div>
<hr>
<div class="container">
    <div class="row">
        <h2> Для связи с нами мяукайте дважды.  </h2>
    </div>
</div>
</body>
</html>

CatMy/main/templates/main/custom_admin.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}{% if subtitle %}{{ subtitle }} | {% endif %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">{{ site_header|default:_('Django administration') }}</a></h1>
{% if user.is_anonymous %}
  {% include "admin/color_theme_toggle.html" %}
{% endif %}
{% endblock %}

{% block nav-global %}{% endblock %}

CatMy/main/templates/main/index.html
{% extends 'main/base_template.html' %}
{% load static %}
{% load bootstrap5 %}
{% block title %}  Новости нашего города - главная {% endblock %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


<div class="single_news" >
    <div class="bg bg-opacity-10 p-4 px-md-5 border rounded" >
        <div class="p-4 p-md-5 text-white rounded" style="background:#4B0082;">
            <h2 class="display-6 fst-italic text-center"> Последняя новость в мире котиков </h2>
        </div>
        <br>
        <div class="col-md-auto">
            <h1 class="display-6 fst-italic text-indigo fw-bold text-center"> {{ article.title }}</h1>
        </div>
        <br>
        <div class="container">
        <div class="col-4"></div>
            <div class="row justify-content-md-center">
        <div class="col-5">
                {% if article.image_set.all %}
                <div id="carouselControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner" role="listbox" style=" width:auto; height: 300px !important;">
                        {% for image in article.image_set.all %}
                        <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                            <img class="d-block p-4 img-responsive img-fluid rounded" src="{{ image.image.url }}">
                        </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                {% endif%}
            </div>
            </div>
        </div>
        <br>
        <div class="container text-white rounded" style="background:#4B0082;">
            <div class="row">
                <div class="col-8">
                    <br>
                    <h6>   Автор: {{ article.author }} </h6>
                    <h6>   Дата публикации: {{ article.date }} </h6>
                    <br>
                </div>
                <div class="col-4">
                    <br>
                    <button class="btn btn-outline-secondary"> <a href="{{ article.get_absolute_url }}" ><i class="fa fa-paw text-white"> Открыть котоновость </i></a></button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CatMy/main/templates/main/list.html
{% extends 'main/base_template.html' %}
{% load static %}
{% load bootstrap5 %}
{% load i18n %}
{% block title %} Новости-главная {% endblock %}

{% block content %}
        <div class="row">
            <div class="text-center" style="margin-top:30px;">
                    <h1 >{% trans 'Новости - главная' %}</h1>
            </div>

             <div class="single_news">
                <div class="p-4 p-md-5 text-white rounded bg-dark" >
                        <div class="col-md-6 px-0">
                          <h1 class="display-4 fst-italic"> {{ article.title }}</h1>
                          <p class="lead my-3">{{ article.anouncement }}</p>
                          <p class="lead mb-0"><a href="{{ article.get_absolute_url }}" class="text-white fw-bold">Полный текст...</a></p>
                        </div>
                  </div>
            </div>
        </div>
{% endblock %}

CatMy/main/templates/main/sidebar.html
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load users_extras %}
{% load i18n %}
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
<script src="https://kit.fontawesome.com/a97047fead.js" crossorigin="anonymous"></script>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

<style>
    aside {
    background-image: url({% static 'main/img/fon.png' %});
    background-repeat: no-repeat;
    background-size: cover;
    position: fixed;
    }
    .one {
    background: #4B0082;
    }
</style>


<aside>
    <div class="page-header text-center">
    <div class="one">
        <div class="d-flex flex-column flex-shrink-0 p-3">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                <img class="bi me-3" src="{% static 'main' %}/img/1.png"  height="10">
                <span class="fs-1 d-none d-lg-block responsive-title"> CatNews </span>
            </a>
            <div class="d-none d-lg-block"> <h7> Главные новости котовселенной </h7> </div>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
               <li class="nav-item bg-white">
                    <a href="{% url 'home' %}" {% if request.resolver_match.view_name  == 'home' %} class="link" aria-current="page" {% endif %}>
                    <div class="d-none d-lg-block" style="color:indigo;"> <i class="fa fa-paw"></i>  Главная </div>
                    </a>
                </li>

                <li class="nav-item bg-white">
                    <a href="{% url 'news' %}" {% if request.resolver_match.view_name  == 'news' %} class="link-active" aria-current="page" {% endif %}>
                    <div class="d-none d-lg-block" style="color:indigo;"> <i class="fa fa-paw"></i>  Все новости</div>
                    </a>
                </li>

                <li class="nav-item bg-white">
                    <a href="{% url 'cats' %}" {% if request.resolver_match.view_name  == 'cats' %} class="link-active" aria-current="page" {% endif %}>
                    <div class="d-none d-lg-block" style="color:indigo;"> <i class="fa fa-paw"></i>  О нас </div>
                    </a>
                </li>

                <li class="nav-item bg-white">
                    <a href="/admin/" {% if request.path  == '/admin/' %} class= "link-active" aria-current="page" {% endif %}>
                    <div class="d-none d-lg-block" style="color:indigo;"> <i class="fa fa-paw"></i>  Котоадмин </div>
                    </a>
                </li>
            </ul>
            <hr>

            {% if request.user.id %}  <!-- проверяем аутентификацию-->
            <div class="dropdown flex-column mb-auto">
                <button class="btn btn-outline-secondary dropdown-toggle col-12" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" style="background:#4B0082;">
                    <img src="{{ request.user.account.account_image.url }}" alt="" width="25" height="25" >
                    <div class="mx-auto"> <h6> {{ request.user.username }} </h6></div>
                </button>
                <ul class="dropdown-menu " aria-labelledby="dropdownMenuButton1">
                    {% if request.user|has_group:"Authors" %}
                        <li><a class="dropdown-item" href="{% url 'create_article' %}"> Создать статью</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{% url 'my_favorites_list' %}"> Избранное</a></li>
                    <li><a class="dropdown-item" href="{% url 'profile' %}"> Мой аккаунт</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'logout' %}"> Выход</a></li>
                </ul>
            </div> <!-- выпадающее меню-->
            {% else %} <!-- ссылки на регистрацию и аутентификацию-->
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item bg-white">
                    <a href="{% url 'registration' %}" {% if request.resolver_match.view_name  == 'registration' %} class="link-active" aria-current="page" {% endif %}>
                    <div class="d-none d-lg-block"  style="color:indigo;"><i class="fa fa-paw"></i> Регистрация</div>
                    </a>
                </li>
                <li class="nav-item bg-white">
                    <a href="{% url 'login' %}" {% if request.resolver_match.view_name  == 'login' %}
                    class="link-active" aria-current="page" {% endif %}>
                    <div class="d-none d-lg-block"  style="color:indigo;"> <i class="fa fa-paw"></i>
                        <i class="{% if request.path  == '/users/login' %} link-active {% endif %}"></i> Вход </div>
                    </a>
                </li>
            </ul>
            {% endif %}
            <br >
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        <hr>
        <div class="input-group ml-auto d-none d-lg-flex" style="width: 100%; max-width: 300px;">
            <form action="{% url 'search' %}" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <input id="search_input" name="search_input" type="text" class="form-control border-0" placeholder="Поиск">
                    <button class="btn btn-outline-secondary"><i class="fa fa-paw text-white"></i></button>
                </div>
            </form>
        </div>
        </div>
    </div>
    </div>
</aside>